### PR TITLE
Add author organization

### LINKED ISSUE #39: Feature: Add filter for organization
The organization information is coming from the `authors` variable in the `dbt_project.yml`:

- [ ] Join this data into the marts
- [ ] Filter inside the dashboard

### PR DESCRIPTION
**Pull request by JCZuurmond**
Add the author organization to the pull requests mart table and use it in the dashboard for the filter. Resolve #39

### CODE REVIEW

**Comment by JCZuurmond** [comment]
Failing soda scan can be ignored.

**Review by ramonvermeulen — DISMISSED** [review]
LGTM!

**Comment by ramonvermeulen** [comment]
-

**Review by jochemloedeman — DISMISSED** [review]

**Review by ramonvermeulen — APPROVED** [review]
tested locally with 3 authors, works fine

**Pull request merged**
