### PR TITLE
Adding folks from GetInData

### PR DESCRIPTION
**Pull request by jessehouwing**
By request of: @kzarzycki

### Checklist

- [ ] When adding a Github handle to be tracked that is not yours, request the user to approve the PR

### CODE REVIEW

**Comment by jessehouwing** [comment]
@kzarzycki please confirm the folks above are OK being included.

**Comment by ramonvermeulen** [comment]
@jessehouwing @kzarzycki 

LGTM! If everyone is OK with being in the list. It is public data, but still.
And do we want to make the distinction between GetInData and Xebia in this case?

FYI data gets updated once a week, so merging won't have immediate effect.

**Review by ramonvermeulen — DISMISSED** [review]

**Comment by JCZuurmond** [comment]
Pinging everyone to let them know that this PR will track their Github contributions. If you want to opt-out, let us know here.

@kzarzycki @mobuchowski @mwiewior @JDarDagran @kristoffSC @maver1ck @szczeles @maciejmacq-dev @andrzejdackiewicz @pawel-big-lebowski @dgniewek @santhin @Lasica @jakubigla @jacops @kacpermuda @calychas @p-pekala @michalrudko @michalbrys @marrrcin

**Comment by JCZuurmond** [comment]
@jessehouwing : Could update the organization to Xebia? A goal is to showcase all Xebia's Github contributions

**Review by JCZuurmond — CHANGES_REQUESTED** [review]
Please change organization to Xebia

**Comment by kristoffSC** [comment]
Hi,
I'm no longer employee of GetInData. 
If you wish to track my open source activity, that's ok with me, however please do not associate it with GetInData nor Xebia.

If you wish to have only "Xeba" guys/activity here, then I would like to ask you to remove me from this list - kristoffSC

**Comment by maver1ck** [comment]
Hi,
I have same situation like @kristoffSC.

Account name: @maver1ck

**Comment by szczeles** [comment]
Same case as guys above (@szczeles)

**Comment by JCZuurmond** [comment]
@jessehouwing : could you update the PR as mentioned in the comments above 👆?

**Comment by jessehouwing** [comment]
Already done

**Comment by JCZuurmond** [comment]
Allright, could you resolve the merge conflict? Then we'll merge this PR

**Review by JCZuurmond — DISMISSED** [review]

**Comment by kzarzycki** [comment]
The issue is, that you folks @maver1ck @szczeles @kristoffSC contributed to a few projects while working at GetInData and the idea was to count those contributions as Getindators' contributions. It's a pity we can't include them as they are very valuable, but I understand your concerns. 
This issue could be solved be implementing in this project a feature to scan only contributors done in some particular period of time. If that was implemented, I would suggest readding your accounts. 

Plus, it's important to have a proper message that these are Xebians/Getindators contributions, not Xebia / Getindata itself (at least not all of them, only those done as work assignment. )

**Pull request merged**
